- hosts: localhost
  
  vars:
    apache_group: 
      Debian: "root" 
      RedHat: "apache"
    apache_ctl: 
      Debian: "/usr/sbin/apache2ctl"
      RedHat: "/usr/sbin/apachectl"

  tasks:
    - yum: pkg=httpd state=present
      when: ansible_os_family == "RedHat"

    - name: Install packages
      apt: update_cache=yes name={{ item }} state=present
      with_items:
        - apache2
        - php5
        - php5-mysql
        - php5-gd
        - libapache2-mod-php5
        - mysql-server

    - name: Make an apachectl symlink that is the same between distros
      file: 
         state: link 
         src: "{{apache_ctl[ansible_os_family]}}"
         dest: /usr/local/bin/apachectl

    - name: Apply index.html from template
      template: 
         src: index.j2 
         dest: /var/www/html/index.html
         group: "{{ apache_group[ansible_os_family] }}"
         mode: "0644"

    - name: Apply index.php from template
      template: 
         src: index.php.j2
         dest: /var/www/html/index.php
         group: "{{ apache_group[ansible_os_family] }}"
         mode: "0644"

    - name: download foo.conf
      get_url: 
         url: http://get.typo3.org/7.6 
         dest: /var/www/ 
         mode: "0440"

#vagrant@vagrant-ubuntu-trusty-64:/var/www$ cd html/ vagrant@vagrant-ubuntu-trusty-64:/var/www/html$ ln -s ../typo3_src-7.6.4 typo3_src vagrant@vagrant-ubuntu-trusty-64:/var/www/html$ ln -s typo3_src/typo3 typo3 vagrant@vagrant-ubuntu-trusty-64:/var/www/html$ ln -s typo3_src/index.php index.php

#vagrant@vagrant-ubuntu-trusty-64:/var/www/html$ touch FIRST_INSTALL

vagrant@vagrant-ubuntu-trusty-64:/var/www/html$ cp typo3_src/_.htaccess .htaccess